[package]
name = "gemini-lib"
version = "0.2.0"
edition = "2021"

[dependencies]
#webpki-roots = "0.26.6"
url = "2.5.2"
native-tls = "0.2.12"
serde = { version = "1", features = ["derive"] }
mime = "0.3.17"
regex = "1.11.1"
